import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://localhost/orangehrm-5.7/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Abandass-');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Abandass-2024');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'PIM' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('link', { name: 'Contact Details' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('run');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('rdeux');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('angers');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('maine');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('');
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.getByRole('textbox').nth(5).fill('49100');
  await page.locator('.oxd-icon.bi-caret-down-fill.oxd-select-text--arrow').click();
  await page.getByRole('option', { name: 'Angola' }).click();
  await page.locator('div:nth-child(6) > .oxd-grid-3 > div > .oxd-input-group > div:nth-child(2) > .oxd-input').first().click();
  await page.locator('.oxd-input.oxd-input--focus').fill('8762123');
  await page.locator('div:nth-child(6) > .oxd-grid-3 > div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('45678');
  await page.locator('div:nth-child(6) > .oxd-grid-3 > div:nth-child(3) > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('div:nth-child(9) > .oxd-grid-3 > div > .oxd-input-group > div:nth-child(2) > .oxd-input').first().click();
  await page.locator('.oxd-input.oxd-input--focus').press('CapsLock');
  await page.locator('.oxd-input.oxd-input--focus').fill('ftyuhijka@hja.com');
  await page.locator('div:nth-child(9) > .oxd-grid-3 > div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('gtafgvb@ju.com');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('ABAKAR GARGOUM').click();
  await page.getByRole('listitem').filter({ hasText: 'ABAKAR' }).locator('i').click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});